### ISSUE TITLE
Missing directories in fpa

### ISSUE THREAD

**Issue by robsyme** [csiro-crop-informatics/fieldprime_server#1]
The fpa/Dockerfile at line [#6](https://github.com/csiro-crop-informatics/fieldprime_server/blob/34b222497d483561cd7c5654c8c6ef7a75af7c16/fpa/Dockerfile#L18) tries to copy `fp_app_api` into the docker image:

``` Dockerfile
COPY fp_app_api /app/fp_app_api
``` 

The same problem occurs on line [#22](https://github.com/csiro-crop-informatics/fieldprime_server/blob/34b222497d483561cd7c5654c8c6ef7a75af7c16/fpa/Dockerfile#L22) with the `sslStuff` directory:

``` Dockerfile
COPY sslStuff /app/sslStuff
```

The problem is that the `fp_app_api` and `sslStuff` directories don't seem to exist in the repository. Are these built elsewhere?

**Comment by alexwhan** [comment]
@taerwin could you have a look at this?

**Comment by taerwin** [comment]
@robsyme sslStuff will need to be created outside of docker as it contains the ssl certificate files (server.crt, server.key) required by apache/flask if you want to run fieldprime in a production mode. I will add some documentation about this. 

fp_app_api is no longer used and should be removed. I will add a fix.

**Comment by robsyme** [comment]
I thought that might be the case for sslStuff, but it's good to know I've not done something dumb to be missing fp_app_api.

**Comment by taerwin** [comment]
I have cleaned up the Dockerfile(s) and added an empty sslCerts directory where ssl certificates will need to be placed to use https.

**Comment by robsyme** [comment]
Thanks taerwin.
